FROM python:3.9-slim

WORKDIR /app

# Install Python dependencies
COPY app/sidecar/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy tracker script
COPY app/sidecar/tracker.py .

CMD ["python", "tracker.py"]
